java_library(
    name = "memory",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/main/java/com/zacharyhirsch/moldynes/emulator:__pkg__",
        "//src/main/java/com/zacharyhirsch/moldynes/emulator/apu:__pkg__",
        "//src/main/java/com/zacharyhirsch/moldynes/emulator/mapper:__pkg__",
        "//src/main/java/com/zacharyhirsch/moldynes/emulator/rom:__pkg__",
    ],
)
