java_library(
    name = "mappers",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/main/java/com/zacharyhirsch/moldynes/emulator:__pkg__",
        "//src/main/java/com/zacharyhirsch/moldynes/emulator/ppu:__pkg__",
        "//src/test/java/com/zacharyhirsch/moldynes/emulator:__pkg__",
    ],
)
