java_library(
    name = "rom",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/main/java/com/zacharyhirsch/moldynes/emulator:__pkg__",
        "//src/main/java/com/zacharyhirsch/moldynes/emulator/mapper:__pkg__",
        "//src/test/java/com/zacharyhirsch/moldynes/emulator:__pkg__",
    ],
)
